js_path /etc/nginx/njs/;

js_import benchmarkOrange from benchmark.njs;

server {
    listen [::]:80;
    server_name benchmark-orange.chidam.xyz;

    location / {
        js_content benchmarkOrange.metrics;
    }
}