server {
	listen [::]:80;
	server_name photos.chidam.xyz;

	# Allow large file uploads
	client_max_body_size 50000M;

	# Disable upload request buffering for faster large uploads
	proxy_request_buffering off;
	client_body_buffer_size 1024k;

	include /etc/nginx/snippets/reverse-proxy-common.conf;

	location / {
		proxy_pass http://100.64.104.52:2283;
		proxy_set_header Upgrade    $http_upgrade;
		proxy_set_header Connection "upgrade";
	}
}